config/routes.rb
Rails.application.routes.draw do
  devise_for :patients
  root to: "pages#home"
  # get "hospitals", to: "hospitals#index"
  # get "hospitals/:id", to: "hospitals#show"
  # get "hospitals/new", to: "hospitals#new", as: :new_hospital
  # post "hospitals", to: "hospitals#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "style", to: "pages#style"

  resources :patients
  resources :categories, only: [:index, :new, :create]
  resources :hospitals_categories, only: [:index]
  resources :appointments, only: [:index, :new, :create, :show, :destroy] do
    get "map", to: "appointments#map", as: "map"
    get "arrived", to: "appointments#arrived", as: "arrived"
    member do
      delete :delete_from_queue
    end
  end
  resources :hospitals, only: [:index, :show, :new, :create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!--<div class="footer footer-links" data-controller="footer" data-footer-target="footer">
    <a href="/">
      <i class="fa-solid fa-house"></i>
      <p class="footer-paragraph">Accueil</p>
    </a>
    <%#= link_to hospitals_path(latitude: params[:latitude], longitude: params[:longitude]) do %>-->
<!--      <i class="fa-solid fa-hospital"></i>
      <p class="footer-paragraph">Hopitaux</p>
    <%# end %>-->
<!--    <a href="/hospitals">
      <i class="fa-solid fa-circle-info"></i>
      <p class="footer-paragraph">Info</p>
    </a>
    <a href="#">
      <i class="fa-solid fa-list"></i>
      <p class="footer-paragraph">RDV</p>
    </a>
  </div>
</div>
-->


<div class="footer footer-links" data-controller="footer" data-footer-target="footer">
  <!-- Lien vers l'accueil -->
  <a href="/">
    <i class="fa-solid fa-house"></i>
    <p class="footer-paragraph">Accueil</p>
  </a>

  <!-- Lien vers la liste des hôpitaux avec latitude et longitude -->
  <% if current_patient && current_patient.appointments.last && current_patient.appointments.last.hospital %>
  <%= link_to hospitals_path(latitude: current_patient.appointments.last.latitude, longitude: current_patient.appointments.last.longitude) do %>
    <i class="fa-solid fa-hospital"></i>
    <p class="footer-paragraph">Hopitaux</p>
  <% end %>
  <% else %>
    <a href="#">
      <i class="fa-solid fa-hospital"></i>
      <p class="footer-paragraph">Hôpitaux</p>
    </a>
  <% end %>


  <!-- Lien vers l'hôpital du dernier rendez-vous -->
  <% if current_patient && current_patient.appointments.last && current_patient.appointments.last.hospital %>
    <%= link_to hospital_path(current_patient.appointments.last.hospital, latitude: current_patient.appointments.last.latitude, longitude: current_patient.appointments.last.longitude) do %>
      <i class="fa-solid fa-circle-info"></i>
      <p class="footer-paragraph">Info</p>
    <% end %>
  <% else %>
    <a href="#">
      <i class="fa-solid fa-circle-info"></i>
      <p class="footer-paragraph">Info</p>
    </a>
  <% end %>

  <!-- Lien vers le détail du dernier rendez-vous -->
  <% if current_patient && current_patient.appointments.last %>
    <%= link_to appointment_path(current_patient.appointments.last, latitude: current_patient.appointments.last.latitude, longitude: current_patient.appointments.last.longitude) do %>
      <i class="fa-solid fa-list"></i>
      <p class="footer-paragraph">RDV</p>
    <% end %>
  <% else %>
    <a href="#">
      <i class="fa-solid fa-list"></i>
      <p class="footer-paragraph">RDV</p>
    </a>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if patient_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_patient_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_patient_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>