config/routes.rb
Rails.application.routes.draw do
  devise_for :patients
  root to: "pages#home"
  # get "hospitals", to: "hospitals#index"
  # get "hospitals/:id", to: "hospitals#show"
  # get "hospitals/new", to: "hospitals#new", as: :new_hospital
  # post "hospitals", to: "hospitals#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "style", to: "pages#style"

  resources :patients
  resources :categories, only: [:index, :new, :create]
  resources :hospitals_categories, only: [:index]
  resources :appointments, only: [:index, :new, :create, :show, :destroy] do
    get "map", to: "appointments#map", as: "map"
    get "arrived", to: "appointments#arrived", as: "arrived"
    member do
      delete :delete_from_queue
    end
  end
  resources :hospitals, only: [:index, :show, :new, :create]
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :online_patient, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
    authorize @patients
  end

  def show
    @patient = Patient.find(params[:id])
    authorize @patient
  end

  def new
    @patient = Patient.new
    authorize @patient
  end

  def create
    @patient = Patient.new(params[:patient])
    @patient.save
    authorize @patient
  end

  def edit
    @patient = Patient.find(params[:id])
    authorize @patient
  end

  def update
    @patient = Patient.find(params[:id])
    authorize @patient
    @patient.update(patient_params)

    redirect_to patient_path(@patient)
  end

  def destroy
    @patient = Patient.find(params[:id])
    authorize @patient
    @patient.destroy

    redirect_to patients_path, status: :see_other
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :online_patient, :email)
  end
end

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>
<%= render 'form', patient: @patient %>
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Patients</h1>
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to "#{patient.first_name} #{patient.last_name} #{patient.online_patient} #{patient.email}", patient_path(patient) %>
      (<%= link_to 'Edit', edit_patient_path(patient) %> |
      <%= link_to 'Delete', patient_path(patient), method: :delete, data: { confirm: 'Are you sure?' } %>)
    </li>
  <% end %>
</ul>
<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>
<%= render 'form', patient: @patient %>
<%= link_to 'Back', patients_path %>