config/routes.rb
Rails.application.routes.draw do
  devise_for :patients
  root to: "pages#home"
  # get "hospitals", to: "hospitals#index"
  # get "hospitals/:id", to: "hospitals#show"
  # get "hospitals/new", to: "hospitals#new", as: :new_hospital
  # post "hospitals", to: "hospitals#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "style", to: "pages#style"

  resources :patients
  resources :categories, only: [:index, :new, :create]
  resources :hospitals_categories, only: [:index]
  resources :appointments, only: [:index, :new, :create, :show, :destroy] do
    get "map", to: "appointments#map", as: "map"
    get "arrived", to: "appointments#arrived", as: "arrived"
    member do
      delete :delete_from_queue
    end
  end
  resources :hospitals, only: [:index, :show, :new, :create]
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  # has_many :hospital_categories, through: :hospital_categories, dependent: :destroy
  has_many :hospital_categories
  has_many :categories, through: :hospital_categories
  has_many :appointments, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: { scope: :address }
  validates :name, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates_length_of :name, minimum: 2, message: "doit contenir au moins 2 caractères"
  validates_length_of :address, minimum: 6, message: "doit contenir au moins 6 caractères"
  
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    if params[:category].present?
      @hospitals = Hospital.joins(:categories).where(categories: { name: params[:category] })
    else
      @hospitals = Hospital.all
    end

    @latitude = params[:latitude].to_f
    @longitude = params[:longitude].to_f

    authorize @hospitals
    @time_per_patient = 20
  end

  def show
    @hospital = Hospital.find(params[:id])
    @time_per_patient = 20
    @appointments = Appointment.all
    @hospital.appointments = @appointments.select do |appointment|
                                                    appointment.hospital.id == @hospital.id
                                                  end
    authorize @hospital
    @categories = @hospital.categories

    @marker = {
        lat: @hospital.latitude,
        lng: @hospital.longitude,
        # info_window_html: render_to_string(partial: "info_window", locals: {hospital: @hospital})
      }

      @latitude = params[:latitude].to_f
      @longitude = params[:longitude].to_f
  end

  def new
    @hospital = Hospital.new
    authorize @hospital
  end

  def create
    @hospital = Hospital.new(params[:hospital])
    @hospital.save
    authorize @hospital
  end

  private

  def hospital_params
    params.require(:hospital).permit(:name, :address, :doctor_nb, :latitude, :longitude)
  end
end

app/views/hospitals/_info_window.html.erb
<h2><%= @hospital.name %></h2>
<p><%= @hospital.address %></p>

app/views/hospitals/index.html.erb
<!-- cards new -->
 <div data-controller="geoloc">
   <div class="mt-3">

    <% @hospitals.each do |hospital| %>

        <div class="card-category-hospital-new no-padding">
          <div class="d-flex flex-column">
            <!--image-->
            <div class="d-flex justify-content-center img-card">
              <%= cl_image_tag hospital.photo.key, crop: :fill, radius: "16:16:0:0", width: 375, height: 280, gravity: :north %>
            </div>

            </div>
            <!--Nom de l'hopital -->
            <h2 class="h2-new"> <%= hospital.name %> </h2>

            <div class="hopital-details-new d-flex justify-content-between padding-card">
              <div class="d-flex flex-column card-width">
                <p class="icon-size address-card"> <%= hospital.address %> </p>
              </div>

              <div class="d-flex justify-content-around flex-column text-end flex-grow-1">
                <div class="d-flex justify-content-start gap-3 icons-new">
                  <div class="flex-column"><p class="icon-size">&nbsp;<i class="fa-solid fa-person-walking"></i></p></div>
                  <div class="flex-column"><p class="icon-size"> &nbsp<%= hospital.distance_to([@latitude, @longitude]).round %> km </p></div>
                </div>
                <div class="d-flex justify-content-start gap-3 icons-new">
                  <div class="flex-column"><p class="icon-size"><i class="fa-solid fa-solid fa-clock"></i></p></div>
                    <% @waiting_minutes = hospital.appointments.length * @time_per_patient %>
                    <% @hours = @waiting_minutes / 60 %>
                    <% @minutes = @waiting_minutes % 60 %>
                  <div class="flex-column">
                    <p class="icon-size">
                      <% if @minutes == 0 %>
                        <%= "#{@hours} h" %>
                      <% elsif @hours == 0 %>
                        <%= "#{@minutes} min" %>
                      <% else %>
                        <%= "#{@hours} h #{@minutes} min" %>
                      <% end %>
                    </p></div>
                </div>
                <div class="d-flex justify-content-start gap-3 icons-new">
                  <div class="flex-column"><p class="icon-size"><i class="fa-solid fa-solid fa-map"></i></p></div>
                  <div class="flex-column"><p class="icon-size"><%= hospital.distance_to([@latitude, @longitude]).round * 5 %> min </p></div>
                </div>
              </div>
            </div>

            <div class="d-flex justify-content-between buttons-card">
              <%= button_to "Détails", hospital_path(hospital), method: :get, class: "btn-primary-home-new", params: { category: params[:category], latitude: @latitude, longitude: @longitude} %>
              <%= button_to "Choisir", appointments_path, method: :post, class: "btn-secondary-home-new", params: { hospital_id: hospital.id, category: params[:category], latitude: @latitude, longitude: @longitude} %>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
  <div class="footer-space"></div>
<!-- cards-end -->

app/views/hospitals/show.html.erb
<%#= cl_image_tag @hospital.photo.key, height: 300, width: 400, crop: :fill %>
<!--<div class="main-container-pixel17 main-container-content">-->

<h1>Détails</h1>

<div class="card-category-hospital-new no-padding">
  <div class="d-flex flex-column">
    <!--image-->
    <div class="d-flex justify-content-center img-card">
      <%= cl_image_tag @hospital.photo.key, crop: :fill, radius: "16:16:0:0", width: 375, height: 280, gravity: :north %>
    </div>
  </div>
  <!--Nom de l'hopital -->
  <h2 class="h2-new"><%= @hospital.name %></h2>

  <div class="hopital-details-new d-flex justify-content-between padding-card">
    <div class="d-flex flex-column card-width">
      <p class="icon-size address-card"><%= @hospital.address %></p>
    </div>
    <div class="d-flex justify-content-around flex-column text-end flex-grow-1">
      <div class="d-flex justify-content-start gap-3 icons-new">
        <div class="flex-column">
          <p class="icon-size">&nbsp;<i class="fa-solid fa-person-walking"></i></p>
        </div>
        <div class="flex-column">
          <p class="icon-size"><%= @hospital.distance_to([@latitude, @longitude]).round %> km</p>
        </div>
      </div>
      <div class="d-flex justify-content-start gap-3 icons-new">
        <div class="flex-column">
          <p class="icon-size">
            <% @waiting_minutes = @hospital.appointments.length * @time_per_patient %>
            <% @hours = @waiting_minutes / 60 %>
            <% @minutes = @waiting_minutes % 60 %>
            <p>
              <i class="fa-solid fa-solid fa-clock"></i>&nbsp;
              <% if @minutes == 0 %>
                <%= "#{@hours} h" %>
              <% elsif @hours == 0 %>
                <%= "#{@minutes} min" %>
              <% else %>
                <%= "#{@hours} h #{@minutes} min" %>
              <% end %>
            </p>
          </p>
        </div>
        <%# <div class="flex-column"><p class="icon-size"> 1h 30 </p></div> %>
      </div>
      <div class="d-flex justify-content-start gap-3 icons-new">
        <div class="flex-column">
          <p class="icon-size"><i class="fa-solid fa-solid fa-map"></i></p>
        </div>
        <div class="flex-column">
          <p class="icon-size"><%= @hospital.distance_to([@latitude, @longitude]).round * 5 %> min</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card-category-hospital-new">
  <h2>Spécialités</h2>

  <% if @categories.any? %>
    <div class="specialities mt-1 mb-3">
      <% @categories.each_with_index do |category, index| %>
        <!-- Chaque bloc de catégories -->
        <%= link_to category.name, "#", class: "btn-specialty-#{index + 1} align-categories" %>
      <% end %>
    </div>
  <% else %>
    <p>Aucune spécialité n'est associée à cet hôpital.</p>
  <% end %>
</div>

<div class="card-category-hospital-new">
  <h2>Localisation</h2>
  <div class='img d-flex justify-content-center'>
    <div
      style="width: 100%; height: 600px;"
      class="mb-3 rounded-5"
      data-controller="map"
      data-map-marker-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <%#= image_tag 'Hospital-pix/itinirary-mini.png', alt: 'Itinirary-mini', style: 'width: 100%; height: auto; overflow: hidden; border-bottom-left-radius: 16px; border-bottom-right-radius: 16px;' %>
  </div>
</div>

<div class="d-flex justify-content-around">
  <%= button_to "Retour", hospitals_path, method: :get, class: "btn-primary-home-new", params: { hospital_id: @hospital.id, category: params[:category], latitude: @latitude, longitude: @longitude } %>
  <%= button_to "Choisir", appointments_path, method: :post, class: "btn-secondary-home-new", params: { hospital_id: @hospital.id, category: params[:category], latitude: @latitude, longitude: @longitude } %>
</div>

<div class="footer-space"></div>
<!--</div>-->